### ISSUE TITLE
[BE] Feat: API 통신을 위한 Controller 구현 - 지현

### ISSUE THREAD

**Issue by yerimsw** [like-a-new-one/like-a-new-one#5]
## Todo List

- [ ] Domain1 Controller, DTO, Dummy Data 구현
- [ ] Domain2 Controller, DTO, Dummy Data 구현

## Deadline
2023.00.00

## Issue Checklist

- [x] Issue Title을 다음과 같이 작성했습니다. (e.g. [BE] Feat: API 통신을 위한 Controller 구현)
- [x] Assignees, Labels, Projects, Milestone을 적절히 선택했습니다.
