### ISSUE TITLE
[BE] Entity 연관 관계 설계 - 지현

### ISSUE THREAD

**Issue by yerimsw** [like-a-new-one/like-a-new-one#7]
## Todo List

- [ ] domain1 Entity 구현
- [ ] domain2 Entity 구현
- [ ] domain3 Entity 구현

## Deadline
2023.00.00

## Issue Checklist

- [x] Issue Title을 다음과 같이 작성했습니다. (e.g. [BE] Feat: API 통신을 위한 Controller 구현)
- [x] Assignees, Labels, Projects, Milestone을 적절히 선택했습니다.
